# Autogenerated by nbdev

d = { 'settings': { 'branch': '',
                'doc_baseurl': '/gpu-python',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/gpu-python',
                'lib_path': 'gpu_python'},
  'syms': {'gpu_python.core': {'gpu_python.core.foo': ('core.html#foo', 'gpu_python/core.py')}}}
