project:
  type: website

website:
  google-analytics: "G-4KGX64DRBZ"
  title: "gpu-python"
  site-url: https://noklam.github.io/gpu-python
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/noklam/gpu-python
      - icon: linkedin
        href: https://linkedin.com/noklamchan
format:
  html:
    theme: cosmo
    css: styles.css



